heat_template_version: 2021-04-16

parameters:
  dns_nameserver:
    type: string

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: OS::stack_name }
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      dns_nameservers:
      - { get_param: dns_nameserver }
      network_id: { get_resource: private_net }
      cidr: "10.0.1.0/24"
      gateway_ip: "10.0.1.1"
      allocation_pools:
        - start: "10.0.1.6"
          end: "10.0.1.254"
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: public
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

outputs:
  OS::stack_id:
    value: { get_resource: private_net }
  network_id:
    value: { get_resource: private_net }
  subnet_id:
    value: { get_resource: private_subnet }